

services:
  localboard:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - .:/app
    environment:
      - DATA_FILE=/app/data/clipboard_data.json
    restart: unless-stopped
    container_name: localboard_app
    command: >
      sh -c "pip install --no-cache-dir watchdog && python -m flask run --host=0.0.0.0 --port=5000 --reload"